# Generated by Django 4.1 on 2022-10-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("edad", models.IntegerField()),
                ("fecha", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="familiar1",
        ),
        migrations.DeleteModel(
            name="familiar2",
        ),
        migrations.DeleteModel(
            name="familiar3",
        ),
    ]
